
#DECLARA O QUE É PRECISO PARA FUNCIONAR A BIBLIOTECA


#DEFINE FUNÇÃO QUE VAI FILTRAR OS TEXTOS (MENOR QUE 240 CARACTERES, EM PORTUGUES, ETC)


#DEFINE AS VARIAVEIS PARA CONTROLE (LIST FROM, LIST TO, ETC)


#DECLARA O SUBREDDIT


#PUXA X POSTS A PARTIR DOS TOP POSTS


#PUXA O COMENTÁRIO MAIS BEM VOTADO QUE PASSE PELO FILTRO


#INSERE O POST NO FROM E O COMENTARIO NO TO


#PUXA 1 REPLY DO COMENTARIO


#ADICIONA O COMENTARIO NO FROM E REPLY NO TO


#PUXA 3 CAMADAS DE REPLIES APÓS O REPLY DO COMENTARIO


#ADICIONA O REPLY PARENT NO FROM E O REPLY NO TO


#TRANSFORMA AS LISTAS FROM E TO EM TXT


#CRIA O ARQUIVO X.FROM E X.TO
